spring.application.name=restaurant_backend
server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5000/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=Asr@1699#

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB